twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        slogan: '@App\Service\Slogan'
        logo: '@App\Service\Logo'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'