vich_uploader:
    db_driver: orm


    mappings:
        article_images:
            uri_prefix:         '%app.path.articles_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.articles_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logo_images:
            uri_prefix:         '%app.path.logo_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.logo_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

